name: spdx
on:
  workflow_dispatch:
  schedule:
    - cron: 12 4 * * 1
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: anchore/sbom-action@v0
        with:
          output-file: manifest.spdx.json
          upload-artifact: false
          upload-release-assets: false
          format: spdx-json
        env:
          SYFT_GOLANG_SEARCH_LOCAL_MOD_CACHE_LICENSES: true
          SYFT_GOLANG_SEARCH_REMOTE_LICENSES: true
          SYFT_JAVASCRIPT_SEARCH_REMOTE_LICENSES: true
      - name: Format spdx
        run: |
          jq . manifest.spdx.json > manifest.spdx.json.tmp
          mv manifest.spdx.json.tmp manifest.spdx.json
      - uses: stefanzweifel/git-auto-commit-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.PINGCI_TOKEN }}
        id: auto-commit-action
        with:
          commit_message: 'chore: regenerate spdx'
          commit_author: Laurel CI <ci@laurel.ai>
          commit_user_name: ping-ci
          commit_user_email: ci@laurel.ai
